# Step 1: Node.js 베이스 이미지 설정
FROM node:20.18.1-alpine

# Step 2: 컨테이너 작업 디렉토리 설정
WORKDIR /app

# Step 3: package.json과 package-lock.json 복사 (의존성 설치를 위해)
COPY package*.json ./

# Step 4: 의존성 설치
RUN npm install --include=dev

# Step 5: 소스 코드 복사
COPY . .

# Step 6: 포트 노출 (NestJS 기본 포트)
EXPOSE 3000